name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello, build job"

      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: setup rust
        uses: ructions/toolchain@v2.0.0

      - name: install trunk
        uses: actions-rs/install@v0.1.2
        with:
          crate: trunk

      - name: build with trunk
        run: trunk build --release

      - name: dir
        run: ls -la ${{ github.workspace }}/dist
  publish:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello, deploy job"
      
      - name: dir
        run: ls -la ${{ github.workspace }}/dist

